apiVersion: v1
kind: Service
metadata:
  name: nba-stat
  labels:
    app: nba-stat
spec:
  selector:
    app: nba-stat
    tier: web
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: "35.232.127.147"
